services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo  
    networks:
      - mern-network
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"

    volumes: 
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mern-network


volumes:
    mongo-data:

networks:
    mern-network:   
