services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on: [api1, api2, api3]

  api1: &api
    build: ./server
    environment:
      - MONGO_URL=mongodb+srv://todo:simplemerntodo@cluster0.risj5y8.mongodb.net/simple-mern-todo?appName=Cluster0
      - INSTANCE_ID=api1
    depends_on: [mongo]


  api2:
    <<: *api
    environment:
      - MONGO_URL=mongodb+srv://todo:simplemerntodo@cluster0.risj5y8.mongodb.net/simple-mern-todo?appName=Cluster0
      - INSTANCE_ID=api2

  api3:
    <<: *api
    environment:
      - MONGO_URL=mongodb+srv://todo:simplemerntodo@cluster0.risj5y8.mongodb.net/simple-mern-todo?appName=Cluster0
      - INSTANCE_ID=api3

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
